version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pg_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meteo
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: weather_api
    restart: always
    depends_on:
      - db
    ports:
      - "6000:5000"
    networks:
      - backend
      - frontend

  admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    volumes:
      - ./server/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db_data: